### ISSUE TITLE
Carrousel > Slick

### ISSUE THREAD

**Issue by goetsu** [atalan/a11y-resources#1]
à mon avis mettre en avant slick dans les scripts de carrousel est une mauvaise idée car son niveau d'accessibilité n'est franchement pas terrible. Il est particulièrement génant notamment car il utilise un aria-live sur les slide qui déclenche la vocalisation non stop à chaque changement de slide

**Comment by Johan-Ramon** [comment]
Effectivement, le [carrousel slick](http://kenwheeler.github.io/slick/) possède malheureusement plusieurs écueils d'accessibilité.
Tout particulièrement l'utilisation d'ARIA non adapté (aria-live="polite", role="listbox", role="option", etc.).

Nous prévoyons de [forker le script](https://github.com/kenwheeler/slick) et de corriger ces problèmes.

D'ici là, dans cette liste de ressources, nous allons introduire la thématique "Rich interface components / Composants d’interface riche" d'une mention indiquant que les librairies et scripts listés ne garantissent pas tous un niveau optimal d'accessibilité.

**Comment by goetsu** [comment]
ok super pour le fork y a déjà des choses dans les tuyaux mais l'auteur de slick semble pas tres réactif https://github.com/kenwheeler/slick/pull/2460
